bootstrap: docker-daemon
from: dlab/two-photon:latest

%help
  First build the docker container:
    docker build -t dlab/two-photon:latest .
  Then build this file (assumes root as build directory):
    sudo singularity build two-photon.sif Singularity
  And then run the container with binds to setup wine
    singularity run \
      --bind "${PWD}/Prairie View":"/APPS/Prairie View/" \
      --bind ${PWD}/profiles:/PROFILES \
      --bind ${PWD}/overview-21:/data \
      two-photon.sif
  And run the rip script!
    /usr/bin/python3 /app/rip.py --directory /data
      
%files
singularity/runscript.sh /runscript.sh

%runscript
    /bin/bash /runscript.sh
